### ISSUE TITLE
Examples folders empty

### ISSUE THREAD

**Issue by JTorresConsulta** [rrag/react-stockcharts-examples#2]
Hi rrag !

I downloaded "react-stockcharts-examples" zip to my PC, but the "examples" folder are empty : )

Other thing: Do you have programmed an auto-update real time JSON data chart?

Thank you !

**Comment by rrag** [comment]
This repo is to automatically create the plunker examples. The source of the examples are [here](https://github.com/rrag/react-stockcharts/tree/master/docs/lib/charts)

> auto-update real time JSON data chart

Have you looked at http://rrag.github.io/react-stockcharts/documentation.html#/updating_data ?
